// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBXtBttvZj4VLvNWvG2UFkcygBfxJKM6ZQ',
    appId: '1:865921270595:web:731e6c639f36f8c77265f6',
    messagingSenderId: '865921270595',
    projectId: 'student-registration-44c3a',
    authDomain: 'student-registration-44c3a.firebaseapp.com',
    storageBucket: 'student-registration-44c3a.appspot.com',
    measurementId: 'G-FEXZ1HL65G',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDt5XJuabYpmuj2wt0xS2fx-w7FMKRpKdc',
    appId: '1:865921270595:android:1e669961f6b8aa497265f6',
    messagingSenderId: '865921270595',
    projectId: 'student-registration-44c3a',
    storageBucket: 'student-registration-44c3a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC8_vb5V3tnXiw4YnIA1rUE2V6VZ_j9wMc',
    appId: '1:865921270595:ios:ad50247f74eb98d07265f6',
    messagingSenderId: '865921270595',
    projectId: 'student-registration-44c3a',
    storageBucket: 'student-registration-44c3a.appspot.com',
    iosBundleId: 'com.example.taskOne',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC8_vb5V3tnXiw4YnIA1rUE2V6VZ_j9wMc',
    appId: '1:865921270595:ios:42c8132a31d0cbbd7265f6',
    messagingSenderId: '865921270595',
    projectId: 'student-registration-44c3a',
    storageBucket: 'student-registration-44c3a.appspot.com',
    iosBundleId: 'com.example.taskOne.RunnerTests',
  );
}
